### ISSUE TITLE
Compression Not Working - Android & iOS

### ISSUE THREAD

**Issue by danielgchap** [jonataslaw/VideoCompress#110]
Hey guys!

I'm having issue with this pub. It seems to me that the compression just... doesn't do anything anymore. 
I'm testing with: 
- Google Pixel 2 (Android 10)
- iPhone 12 (iOS 14.2)

Implementing the package is pretty simple but here is my code (I am using a dialog just to illustrate the lack of compression for this post)..

`static compressvideo(File video, BuildContext context) async {
    _subscription = VideoCompress.compressProgress$.subscribe((progress) {});
    final info = await VideoCompress.compressVideo(video.path,
        includeAudio: true, quality: VideoQuality.MediumQuality, frameRate: 24);

    showDialog(
      context: context,
      builder: (builder) => CustomDialog(
        buttonText: "OK",
        title: "Video Analytics",
        description:
            "PRE COMPRESS: ${video.lengthSync()}\nPOST COMPRESS: ${info.filesize}",
      ),
    );
}`

This gives the following output:
![IMG_0067](https://user-images.githubusercontent.com/48697774/119363460-d2e2a480-bc7b-11eb-9ce9-96ec347e4c50.JPG)

PRE COMPRESSED VIDEO: 4,795,933
POST COMPRESSED VIDEO: 4,791,804

I've used flutter_video_compress but that doesn't seem to work on Android anymore.
I've used ffmpeg (may post on their repo too) but have only had success compressing video with a black screen and video audio.

Any suggestions/inputs/direction would be really great. Thanks!

**Comment by danielgchap** [comment]
I did get it to compress using LowQuality and a frame rate of 24:

    final info = await VideoCompress.compressVideo(video.path,
        deleteOrigin: false,
        includeAudio: true,
        quality: VideoQuality.LowQuality,
        frameRate: 24);

POST COMPRESSED VIDEO WENT TO ABOUT: 1.5MB. 
Will have to do for now I guess. 

Thanks!

**Comment by yanivshaked** [comment]
@danielgchap Please close this issue if it is solved

**Comment by danielgchap** [comment]
Hi @yanivshaked I truly mean no disrespect but that is your role. To mitigate the issue, QA and resolve. I'm not using this library anymore. Thanks boss.

**Comment by yanivshaked** [comment]
Sorry, I didn't mean any disrespect. I was merely asking that **if** the issue is solved, you should close it. If it is not, I can suggest you try the latest new compression quality modes (last 4 values are new):

```
enum VideoQuality {
  DefaultQuality,
  LowQuality,
  MediumQuality,
  HighestQuality,
  Res640x480Quality,
  Res960x540Quality,
  Res1280x720Quality,
  Res1920x1080Quality
}
```

**Comment by danielgchap** [comment]
@yanivshaked me neither bro. Sorry. Oh nice!!!!! I will def check these out bro. Thank you so much. Apologies. You are right in what you are asking (I'm having a bad day can you tell lol. ) I appreciate you my brother!!!

**Comment by yanivshaked** [comment]
@danielgchap Hope your day gets better soon!!!
In order to use the new compression modes, you should use the latest version of the plugin, until @jonataslaw provides a new release:
```
video_compress:
  git:
    url: https://github.com/jonataslaw/VideoCompress
    ref: "583e700"
```

**Comment by danielgchap** [comment]
Will do! @yanivshaked thank you so much!

**Comment by danielgchap** [comment]
Just wanted to let you know that the compression is drastically improved! Thank you so much for your hard work and all the effort you put into this!
