### ISSUE TITLE
iOS compression is same for high or medium or low or default

### ISSUE THREAD

**Issue by nagarjunvv** [jonataslaw/VideoCompress#112]
I tried to compress the video but when i test with different qualities the video size is same for high or medium or low or default.

Can you please help me how to fix this issue.

final info = await VideoCompress.compressVideo(
                          file2.path,
                          quality: VideoQuality.HighestQuality, // i tried all options here
                          deleteOrigin: false,
                        );
                        file = File(info!.path!);

**Comment by nagarjunvv** [comment]
changing file picker to image picker solved the issue. Thanks

**Comment by yanivshaked** [comment]
@nagarjunvv  Please close this issue if you have solved it

**Comment by abdullah432** [comment]
Same issue on android
