### ISSUE TITLE
Transcoder nuget getting path issue while compressing video in Android xamarin fomrs

### ISSUE THREAD

**Issue by sbs-surendhar-kabilan** [jonataslaw/VideoCompress#121]
Karamunting.Android.Natario1.Transcoder 0.9.1 version while video compress and upload video No such file or directory issue came

Java.Interop
JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
Java.Interop
JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
OtaliaStudios.TranscoderLib
TranscoderOptions+Builder.Transcode ()
AutoVHC.Droid
VideoTranscoder+AVAssetExportSession.ExportTaskAsync ()
AutoVHC.Droid
VideoTranscoder.TranscodeVideoAsync (System.String sourceVideoPath, System.String outputpath)
AutoVHC.Droid
MediaReader.GetCompressedVideo (System.String inputPath, System.String outputPath)
java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/Android/data//Movies/555788_1014502385_29-4-2021-2-12-5-7426.mp4 (No such file or directory)
com.otaliastudios.transcoder.source.FilePathDataSource.ensureDescriptorSource FilePathDataSource.java:43
com.otaliastudios.transcoder.source.FilePathDataSource.applyExtractor FilePathDataSource.java:50
com.otaliastudios.transcoder.source.DefaultDataSource.ensureExtractor DefaultDataSource.java:49
com.otaliastudios.transcoder.source.DefaultDataSource.getTrackFormat DefaultDataSource.java:178
com.otaliastudios.transcoder.TranscoderOptions$Builder.buildAudioDataSources TranscoderOptions.java:340
com.otaliastudios.transcoder.TranscoderOptions$Builder.build TranscoderOptions.java:401
com.otaliastudios.transcoder.TranscoderOptions$Builder.transcode TranscoderOptions.java:417
Caused by: java.io.FileNotFoundException: 
java.io.FileInputStream.open(Native Method)
java.io.FileInputStream.<init> FileInputStream.java:146
java.io.FileInputStream.<init> FileInputStream.java:99
com.otaliastudios.transcoder.source.FilePathDataSource.ensureDescriptorSource FilePathDataSource.java:39

**Comment by jonataslaw** [comment]
Xamarin forms????

Please, when opening an issue in a repository, try to be clear, and check if it is related to your problem.
This is a Flutter package. Since this issue is completely inept, I'm closing it.
