### ISSUE TITLE
Could not resolve com.otaliastudios:transcoder:0.9.1.

### ISSUE THREAD

**Issue by walikhan226** [jonataslaw/VideoCompress#156]
Could not resolve com.otaliastudios:transcoder:0.9.1.
     Required by:
         project :app > project :video_compress
      > Could not resolve com.otaliastudios:transcoder:0.9.1.
         > Could not get resource 'https://jcenter.bintray.com/com/otaliastudios/transcoder/0.9.1/transcoder-0.9.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/otaliastudios/transcoder/0.9.1/transcoder-0.9.1.pom'. Received status code 502 from server: Bad Gateway

**Comment by milkyway044** [comment]
+1

**Comment by walikhan226** [comment]
closing this
