### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.

### ISSUE THREAD

**Issue by xiaocode337317439** [jonataslaw/VideoCompress#168]
`
loacl ==>> kotlin-gradle-plugin:1.6.10

The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.
The following dependencies do not satisfy the required version:
project ':video_compress' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.31
`

**Comment by bhanu-under25** [comment]
What was the resolution? @xiaocode337317439
