### ISSUE TITLE
iOS - crash while compressing video

### ISSUE THREAD

**Issue by khainhero** [jonataslaw/VideoCompress#2]
iOS crashes when compressing a video with real device and iOS simulator

**Potential fix:**
Getting the MediaInfo of the original File before compressing the video

```
MediaInfo _originalInfo = await videoCompress.getMediaInfo(originalVideoPath);
MediaInfo _compressedVideo = await videoCompress.compressVideo(originalVideoPath);
```

**Comment by adamdupuis** [comment]
Was this resolved? My iOS device crashes at `compressVideo()` with this plugin (2.0.0 from pub) as well as [flutter_video_compress](https://pub.dev/packages/flutter_video_compress) without any errors. The potential fix mentioned doesn't change anything.
