### ISSUE TITLE
"Failed to stop the muxer" error using video_compress 3.1.1

### ISSUE THREAD

**Issue by marinaaraujo97** [jonataslaw/VideoCompress#203]
Hello, 

I have a mobile app in Flutter where I allow users to upload videos.
I compress them using `video_compress: ^3.1.1` and then upload them to a server. 

While running on some devices throws the `java.lang.IllegalStateException: Failed to stop the muxer` error

After some testing I figured that this error only happens if I use the parameter `includeAudio: true`, if it is set to `false `the error does not occur but, as you might understand, a video without audio loses its purpose. 

I cannot reproduce the error since on my test devices it works fine but not on the personal device of some users, they only allowed me to test it for a short period time.

Can someone help on this issue? 

Thanks in advance.

**Comment by qusai-alhallak** [comment]
Same bug for me

**Comment by jonataslaw** [comment]
Does this happen on any version of android?

**Comment by jonataslaw** [comment]
Maybe related to https://github.com/jonataslaw/VideoCompress/pull/189

**Comment by marinaaraujo97** [comment]
> Does this happen on any version of android?

I was allowed to test this on two devices that showed the error. 
On a Huawei which I'm not sure what android version it has. And on a Redmi Note 7, with MIUI 12.5.1 and Android 10.

The devices I develop in (which do not present the error) include a S22 Ultra, a S22+ and a Redmi Note 9S therefore I believe newer android versions are not the problem.

> Maybe related to #189

I've seen that thread before yet I'm not sure what `rollback transcoder version to 0.9.1` since I'm only using `video_compress` and it has no 0.9.1 version released.

**Comment by qusai-alhallak** [comment]
@jonataslaw 
I face the problem on  Redmi Note 7 with Android 10 version and on Infinix X650C with Android 9 version

**Comment by jonataslaw** [comment]
Unfortunately I was unable to reproduce the error.

Could any of you replace the package in pubspec with this one and check if the problem occurs with the latest changes?


```yaml
video_compress:
    git:
      url: https://github.com/jonataslaw/VideoCompress.git
      ref: master
```

**Comment by marinaaraujo97** [comment]
@qusai-alhallak 
Could you please try what @jonataslaw  said and give feedback? 

Like I said, I also have issue on a Redmi Note 7 but I don't have access to the phone to test it since it's a user's personal phone.

I'd apprecciate it a lot!

**Comment by kostasoft** [comment]
> Could any of you replace the package in pubspec with this one and check if the problem occurs with the latest changes?

It works, thank you!

**Comment by qusai-alhallak** [comment]
@marinaaraujo97 
it works, on Redmi note 7 
thank you @jonataslaw you can close the issue

**Comment by marinaaraujo97** [comment]
Thank you so much for testing @qusai-alhallak 
I'll replace the package and release the app update
