### ISSUE TITLE
compression duration is not working as expected

### ISSUE THREAD

**Issue by legend1998** [jonataslaw/VideoCompress#205]
there is lack of info of duration parameter, whether it takes milliseconds or seconds,
the problem is duration parameter takes seconds as input and compressed video duration is not in seconds .

for example 

i compressed a video of 67 seconds duration and gave start parameter 0, and duration parameter 60,
the output compressed video is 6 second duration.

Any suggestion or hint may work for me.

**Comment by temirfe** [comment]
my video was 28 sec, i gave startTime 0, duration 10 (to get first 10 secs) but it returned first 18 secs. Seems like duration is for cutting, but i don't know why it cut 10 secs from end

**Comment by heshesh2010** [comment]
+1

**Comment by angelogullotta** [comment]
It's not intuitive but I think duration = time (seconds) to trim from the end of the video.

**Comment by legend1998** [comment]
Well seems like @angelogullotta is right. closing this is issue. 

I suppose this parameter instruction is updated on newer upcoming versions.

**Comment by pick8chu** [comment]
This should be reopened, considering the documentation has not been updated
