### ISSUE TITLE
Android - Video Compressing subscription stream not working

### ISSUE THREAD

**Issue by shubham-chhimpa** [jonataslaw/VideoCompress#21]
The video compressing subscription stream does not emit any progress data.

**Comment by hungtran2492** [comment]
I have the same issue. Can you check this?

**Comment by crtl** [comment]
Ok, thanks to the following lines:

```dart
// video_compressor.dart

factory VideoCompress() {
    if (_instance == null) _instance = VideoCompress._();
    return _instance;
  }

  VideoCompress._() {
    _channel.setMethodCallHandler(_progresCallback);
  }
```

You have to call `VideoCompress()` constructor at least once for `compressProgress$` to work.

**Comment by jonataslaw** [comment]
> Ok, thanks to the following lines:
> 
> ```dart
> // video_compressor.dart
> 
> factory VideoCompress() {
>     if (_instance == null) _instance = VideoCompress._();
>     return _instance;
>   }
> 
>   VideoCompress._() {
>     _channel.setMethodCallHandler(_progresCallback);
>   }
> ```
> 
> You have to call `VideoCompress()` constructor at least once for `compressProgress$` to work.

You're right

**Comment by yy1300326388** [comment]
@jonataslaw @shubham-chhimpa Mine is that iOS has no compression progress, Android has

**Comment by ukuleleplayer** [comment]
Can confirm. As mentioned above, the fix is as simple as calling the constructor once.
Nice tool!

**Comment by VikashIOS** [comment]
@crtl @jonataslaw @ukuleleplayer did you find the solution. I need help in this please share the solutions.

**Comment by wildsurfer** [comment]
Same issue

**Comment by crtl** [comment]
@VikashIOS @wildsurfer Do you even read? Or just post IDK?

**Comment by shubham-chhimpa** [comment]
> Ok, thanks to the following lines:
> 
> ```dart
> // video_compressor.dart
> 
> factory VideoCompress() {
>     if (_instance == null) _instance = VideoCompress._();
>     return _instance;
>   }
> 
>   VideoCompress._() {
>     _channel.setMethodCallHandler(_progresCallback);
>   }
> ```
> 
> You have to call `VideoCompress()` constructor at least once for `compressProgress$` to work.

Yes this worked for me.
Thanks !

For those who want the solution

Just add this line to the initState() function

```dart
    VideoCompress videoCompress = new VideoCompress();
```
This code looks like.

```dart
 @override
  void initState() {
    VideoCompress videoCompress = new VideoCompress();
    super.initState();
    _subscription =
        VideoCompress.compressProgress$.subscribe((progress) {
          debugPrint('myprogress: ${progress}');
        });
  }
```
