### ISSUE TITLE
'compressVideo' returns null

### ISSUE THREAD

**Issue by meridorkobi** [jonataslaw/VideoCompress#222]
The VideoCompress function return null value

`      final info = await VideoCompress.compressVideo(
        file,
        quality: VideoQuality.MediumQuality,
        deleteOrigin: false,
        includeAudio: true,
      );

video_compress: ^3.1.2

File path 
`/data/user/0/com.xxxx/app_flutter/trimmervideo/VID-20221228-WA0004_trimmed:Jan29,2023-16:26:22.mp4`

file size = 1055966 bytes

**Comment by jomch** [comment]
I'd like to replace with ffmpeg

**Comment by kobimeridor** [comment]
Which plugin?

**Comment by meridorkobi** [comment]
I moved to compress, it was after the trimmer and I moved to before the trimer and its working

**Comment by meridorkobi** [comment]
Cloesed

**Comment by Junesui** [comment]
> Closed

i get mediainfo is null . how to solved it.
