### ISSUE TITLE
#Issue Could not find com.otaliastudios:transcoder:0.9.1.

### ISSUE THREAD

**Issue by InspectlyMads** [jonataslaw/VideoCompress#240]
I can no longer build the application due to this failure. Anyone else experiencing the same?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeAppCenterReleaseArtProfile'.
> Could not resolve all files for configuration ':app:appCenterReleaseRuntimeClasspath'.
   > Could not find com.otaliastudios:transcoder:0.9.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/otaliastudios/transcoder/0.9.1/transcoder-0.9.1.pom
       - https://repo.maven.apache.org/maven2/com/otaliastudios/transcoder/0.9.1/transcoder-0.9.1.pom
       - https://jcenter.bintray.com/com/otaliastudios/transcoder/0.9.1/transcoder-0.9.1.pom
       - https://storage.googleapis.com/download.flutter.io/com/otaliastudios/transcoder/0.9.1/transcoder-0.9.1.pom
       - https://plugins.gradle.org/m2/com/otaliastudios/transcoder/0.9.1/transcoder-0.9.1.pom
       - https://jitpack.io/com/otaliastudios/transcoder/0.9.1/transcoder-0.9.1.pom
       - file:/Users/runner/.m2/repository/com/otaliastudios/transcoder/0.9.1/transcoder-0.9.1.pom
     Required by:
         project :app > project :video_compress

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by abdallah-gaber-hoods** [comment]
Same here

**Comment by MattyBoy4444** [comment]
Same

**Comment by Pro-Lakshman** [comment]
Same Here

**Comment by MattyBoy4444** [comment]
Check out https://github.com/kamaravichow/VideoCompressPlus. 
Note: for iOS you need to get the PR I just submitted to this package.  This package doesn't seem maintained.

https://github.com/kamaravichow/VideoCompressPlus/pull/1

**Comment by GabrielAraujo** [comment]
This one is fully working on android and iOS
```
  video_compress:
    git:
      url: https://github.com/SpectoraSoftware/VideoCompress
      ref: master
```

**Comment by MattyBoy4444** [comment]
Thanks.  I'll give yours a try.  Mine still had something wrong with the damn imports

**Comment by ashanftw** [comment]
I tried 

1. @GabrielAraujo 's solution 
2. add jcenter()

but still Getting the same error. seems like transcoder/0.9.1 version has removed from the servers. could you please update the video_compress with latest transcoder version

**Comment by GabrielAraujo** [comment]
I was able to create builds using the repo I created on https://github.com/SpectoraSoftware/VideoCompress. It uses the transcoder more recent versions

**Comment by ashanftw** [comment]
> I was able to create builds using the repo I created on https://github.com/SpectoraSoftware/VideoCompress. It uses the transcoder more recent versions

ill give it a try again.

**Comment by kaushiktechnoproject** [comment]
video_compress:
    git:
      url: https://github.com/SpectoraSoftware/VideoCompress
      ref:  master
      
      
      this is working for me

**Comment by ashanftw** [comment]
Yesterday I was able to build the application without any issue. I didn't do any change. Seems like servers are up now

**Comment by rcsousa14** [comment]
> This one is fully working on android and iOS
> 
> ```
>   video_compress:
>     git:
>       url: https://github.com/SpectoraSoftware/VideoCompress
>       ref: caf41183e84adebd6ef5c8fba547937daf556a65 # Or master?
> ```

Thank you so much for this. However, on the compressVideo() method could the startTime and duration be double instead of int?

**Comment by rcsousa14** [comment]
can some please help me trying to get this working.

**Comment by jitendrakohar** [comment]
you have to add the maven link in the build.gradle files, you can find the procedure for solving the problem by visiting on stackoverflow link.

[https://stackoverflow.com/questions/75070808/build-failed-in-flutter-app-due-to-video-compress-package/77647670#77647670](url)

**Comment by tomcatvr** [comment]
Hi, adding the jcenter() repository to the build.gradle file solved the problem

allprojects {
repositories {
google()
mavenCentral()
jcenter() // Needed by video_compressor
}
}

**Comment by arthurgiani** [comment]
This started to happen on my build yestarday. It suddenly worked and then failed again.

@GabrielAraujo suggestion worked well.

**Comment by benedictcontawe** [comment]
same thing

Failed to resolve: com.otaliastudios:transcoder:0.9.1
Show in Project Structure dialog
Affected Modules: app
