### ISSUE TITLE
Cannot compress more than one video, getting error

### ISSUE THREAD

**Issue by PavieOlivier** [jonataslaw/VideoCompress#26]
I cannot compress more videos after compressing the 1st one I get that error
```
Bad state: Stream has already been listened to.
```
This happens whenever I go back to a page inside the ''initState'' method

**Comment by syahrizalakbar** [comment]
i have the same too although i have unsubscribed in dispose method

**Comment by syahrizalakbar** [comment]
i think that because this is using Singleton, and after unsubscribe Stream, you cannot reinitialize the stream, the solution is you can reset compressProgress$ with this code in initState


VideoCompress.compressProgress$ = ObservableBuilder<double>();

**Comment by yanivshaked** [comment]
Or you can wrap VideoCompress.compressProgress$ with StreamController that supports multiple subscriptions:
```
static StreamController<double> _progressStreamController = StreamController<double>();
static Stream<double> progressStream = _progressStreamController.stream.asBroadcastStream();
.
.
.
VideoCompress.compressProgress$.subscribe((value) {
  _progressStreamController.sink.add(value / 100);
});

```

and register the stream in your widget:
```
  @override
  void initState() {
    super.initState();
    if (widget.progressStream != null) {
      _progressSusbscription = widget.progressStream.listen((p) {
        setState(() {
          _progress = p;
        });
      });
    }
  }
```

**Comment by jonataslaw** [comment]
Fix um last version

**Comment by ribesh-code** [comment]
### `Video compress: 3.1.0`

[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale
    en-NP)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.2)

I am still facing the issue where multiple video cannot be compressed. any possible solutions?

**Comment by tenhobi** [comment]
@jonataslaw this issue still preserves. Can we replaca the `ObservableBuilder<double>()` with `StreamController<double> _progressStream = StreamController.broadcast();` to fix this?
