### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by jxstxn1** [jonataslaw/VideoCompress#265]
Are there any plans in the foreseeable future that a new release will land on pub.dev?
The last update on pub.dev is 20 months old. The master branch here only 2.

The big problem is that the provided fix in #263 is not working anymore since `com.otaliastudios:transcoder` was removed from https://plugins.gradle.org/m2/.
So it would be great to have a release where this dependency is bumped.

**Comment by nafiskabbo** [comment]
Same issue

**Comment by aleksei-verbitski-m10** [comment]
Same here
please publish the new release to pub.dev

**Comment by arthurgiani** [comment]
Same

**Comment by ZachSelindh** [comment]
@jonataslaw Any chance of getting an update here?

**Comment by steveeyring** [comment]
Using version 3.1.3 I am getting the error: 

Execution failed for task ':video_compress:generateDebugRFile'.
> Could not resolve all files for configuration ':video_compress:debugCompileClasspath'.
   > Could not find com.otaliastudios:transcoder:0.9.1.
     Required by:
         project :video_compress
