### ISSUE TITLE
Compressing Video Takes Too Long

### ISSUE THREAD

**Issue by aatabong** [jonataslaw/VideoCompress#28]
I don't know if its just me but compressing videos takes over like 10 minutes for me. 

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18362.900], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.46.1)
[√] Connected device (1 available)

• No issues found!

**Comment by jonataslaw** [comment]
Compression is faster than it can be. Mobile devices are not as powerful as a real computer.
