### ISSUE TITLE
Video increases in size instead of compressing[Bug]

### ISSUE THREAD

**Issue by freakcsh** [jonataslaw/VideoCompress#29]
Video increases in size instead of compressing
 MediaInfo mediaInfo = await VideoCompress.compressVideo(
      path,
      quality: VideoQuality.DefaultQuality,
      deleteOrigin: false,
    );

**Comment by freakcsh** [comment]
Through testing, I found that if it is a video that has been compressed, it will become larger when the library is used again for compression, but it will not become larger when shooting video compression directly.

**Comment by VikashIOS** [comment]
How I will check that video is already compressed so that I can avoid this issue?

**Comment by abdullah432** [comment]
I'm uploading a WhatsApp video, I know it's compressed but how can I make a check to avoid its compression? 
After compressing 2MB video it become 11MB
