### ISSUE TITLE
file not found     #import <video_compress/video_compress-Swift.h>

### ISSUE THREAD

**Issue by MrQiu920702** [jonataslaw/VideoCompress#35]
ios  
/Users/dongjieqiu/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/video_compress-2.0.0/ios/Classes/VideoCompressPlugin.m:2:9: fatal error: 'video_compress/video_compress-Swift.h' file not found
    #import <video_compress/video_compress-Swift.h>

**Comment by hatemragab** [comment]
is there any progress ?

**Comment by dcr309duan** [comment]
Same problem.

**Comment by liuweichn** [comment]
Same problem.

**Comment by IgreatD** [comment]
Same problem.

**Comment by jonataslaw** [comment]
You need to have swift on your project.
This project was built with swift and kotlin, you need to support both languages.

solutions:
Method 1: exclude ios folder and run on terminal:

`flutter create .` (don't forget dot)
__________
Method 2:
add to ios/Podfile
`use_frameworks!`

example:
```
use_frameworks! 
system('rm -rf .symlinks')
system('mkdir -p .symlinks/plugins')
```

and swift version:
`config.build_settings['SWIFT_VERSION'] = '5.0'`

example:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '5.0' # added this
    end
  end
end
```

As this is not a problem related to the plugin, but rather about using Flutter, I am closing this.

**Comment by wutingyu** [comment]
I used method 1(flutter create .) , but it stills  not work?

**Comment by ArefMozafari** [comment]
I used the both solutions and none of them works.
What should we do?

**Comment by NightSkyWatchers** [comment]
I used method 2 , it works

**Comment by lavande820** [comment]
> I used method 2 , it works

Hello, may I ask how you added "use_frameworks!" to the Podfile file?

**Comment by NightSkyWatchers** [comment]
> > I used method 2 , it works
> 
> Hello, may I ask how you added "use_frameworks!" to the Podfile file?

Open the podfile in Android studio and add it as follows
![image](https://github.com/jonataslaw/VideoCompress/assets/14065529/3bd49fa9-de75-47d5-88cc-5cc20fee42b5)

**Comment by LindaSze** [comment]
I can't add [ use_frameworks!],cause it will make other mistake about libraries.
so, is there any other solution?

**Comment by pranavo72bex** [comment]
> I can't add [ use_frameworks!],cause it will make other mistake about libraries. so, is there any other solution?

Did you find any way to fix the issue without using `use_frameworks!`

**Comment by rignaneseleo** [comment]
same problem here, any real fix?

**Comment by urvish-sojitra-seaflux** [comment]
I have used Zoom Video SDK for running the dependency packages of the Zoom I have to remove 
`use frameworks!`

and When using video compress package I have to use that `use frameworks!` for ios and due to that the build was not created in the ios.

But when Added the below code it worked that I have taken from Method 2.

and swift version:
`config.build_settings['SWIFT_VERSION'] = '5.0'`

**Comment by lampemw** [comment]
@pranavo72bex Did you ever find a solution for this? My flutter project needs to remove `use_frameworks!` and I can't build because of this issue.

**Comment by e23awais** [comment]
Ok so solution is adding use_frameworks! . but if someone have issues with other plugins if they use this 
then they can use 
use_frameworks! :linkage => :static
instead of that...... This is fix for me hope so for others as well
