### ISSUE TITLE
Android, IOS - green and Blurry lines

### ISSUE THREAD

**Issue by khainhero** [jonataslaw/VideoCompress#4]
For a vertical aspect ratio video, the blurry/green lines appear on the right side of the video from top to bottom

For a horizontal based aspect ratio, the blurry/green lines appear on the bottom of the video spanning from left to the right

**Issue only appears in VideoPlay plugin**, works fine when viewing the file in Chrome from firebase storage.

Sending a video from **Android to Android** where the **quality** is set to **LowQuality** has a blurry line. And also sending **Android to IOS** has blurry lines shown

_Other quality presets, it is working fine._

Sending video compressed with **iOS device**(can be sent from iOS simulator as well), to an **Android device** shows a green line instead of blurry line. 

When compressed on iOS, depending on the quality preset the green line gets bigger. For example using LowQuality preset shows a much bigger green line disturbance on video.

It works fine when viewing on Chrome from firebase storage.

**Viewing the video on iOS device works great**

**Comment by jonataslaw** [comment]
This is related to presets and will be resolved here:
https://github.com/jonataslaw/VideoCompress/issues/6
