### ISSUE TITLE
Keep the video resolution (dimensions)

### ISSUE THREAD

**Issue by jpiabrantes** [jonataslaw/VideoCompress#42]
Is there a way to keep the video dimensions? I want to compress a video not to change its dimensions.

**Comment by jonataslaw** [comment]
Compression is literally the reduction of frames per second and frame size.
So this is not possible

**Comment by jpiabrantes** [comment]
> Compression is literally the reduction of frames per second and frame size.
> So this is not possible

It is not. See [Wikipedia](https://en.wikipedia.org/wiki/Data_compression) they talk about lossless, lossy, machine learning, image differencing, inter-frame compression, but not about reduction of fps or frame size. That is not compression, you are not compressing anything, just throwing data out.

**Comment by jonataslaw** [comment]
Apple has pre-defined compression models. 

AVAssetExportPresetLowQuality
AVAssetExportPresetMediumQuality
AVAssetExportPresetHighQuality

Perhaps if the concept of native compression is not enough for you, you need to create your own algorithm for this.
We simply use what the native code (and standard recommendations) offers us.

**Comment by jpiabrantes** [comment]
Just don't call it compression it will confuse many users. Apple doesn't
call it compression either, these are quality presets.

You can compress a cake: make it occupy less volume (size) with the same
mass (data) by pushing (compress) it against something. Or you can throw a
slice of the cake to the garbage which will free-up some size in your
fridge, but it is not called compression.
