### ISSUE TITLE
Using the HighestQuality increases the video size

### ISSUE THREAD

**Issue by jpiabrantes** [jonataslaw/VideoCompress#43]
I can't understand what this package is doing. When I use the Medium Quality it outputs my video with a smaller resolution. This is not compression is just downsampling. When I use the Highest Quality my video increases in size.

**Comment by Hynsen** [comment]
I have the same question

**Comment by jpiabrantes** [comment]
The author of this package replied here (https://github.com/jonataslaw/VideoCompress/issues/42#issuecomment-697326622)

This package doesn't do compression. It simply changes the resolution of the videos (downsampling and upsampling them).

**Comment by Hynsen** [comment]
> The author of this package replied here ([#42 (comment)](https://github.com/jonataslaw/VideoCompress/issues/42#issuecomment-697326622))
> 
> This package doesn't do compression. It simply changes the resolution of the videos (downsampling and upsampling them).

Yeah,i get it,tks!
