### ISSUE TITLE
Compression crashes

### ISSUE THREAD

**Issue by Engelbrekt39** [jonataslaw/VideoCompress#61]
I tried compressing video both on emulator and real device running Android 10 and it keeps on crashing. What am I doing wrong? Below is my code.

`  void getVideo() async {
    final picker = ImagePicker();

    final pickedFile = await picker.getVideo(source: ImageSource.camera,maxDuration: Duration(seconds: 10));
    File file = File(pickedFile.path);
    MediaInfo mediaInfo = await VideoCompress.compressVideo(
      file.path,
      quality: VideoQuality.DefaultQuality,
      deleteOrigin: false,
      includeAudio: true,// It's false by default
    );
    // print('Our picked video is: ${mediaInfo.path}');

    if(mediaInfo!=null){
      file = mediaInfo.file;

      // await compressAndGetFile(file).then((thumbnail) {
      setState(() {
        widget.onVideoIconSelected(file);
      });
    }

    // });
  }`

and log:

`I/DefaultVideoStrategy(29098): Input width&height: 720x1280
I/DefaultVideoStrategy(29098): Output width&height: 720x1280
V/Engine  (29098): Duration (us): 27230860000
V/Engine  (29098): new step: 0
I/OMXClient(29098): IOmx service obtained
I/OMXClient(29098): IOmx service obtained
I/OMXClient(29098): IOmx service obtained
W/OMXUtils(29098): do not know color format 0x7f000789 = 2130708361
I/ACodec  (29098): setupAVCEncoderParameters with [profile: Baseline] [level: Level41]
I/ACodec  (29098): [OMX.google.h264.encoder] cannot encode color aspects. Ignoring.
I/ACodec  (29098): [OMX.google.h264.encoder] cannot encode HDR static metadata. Ignoring.
I/ACodec  (29098): setupVideoEncoder succeeded
W/OMXUtils(29098): do not know color format 0x7f000789 = 2130708361
D/HostConnection(29098): HostConnection::get() New Host Connection established 0xc74c5b60, tid 29695
D/HostConnection(29098): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
D/eglCodecCommon(29098): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(29098): eglCreateContext: 0xf777fd00: maj 3 min 0 rcv 3
D/EGL_emulation(29098): eglMakeCurrent: 0xf777fd00: ver 3 0 (tinfo 0xc7601590)
I/OMXClient(29098): IOmx service obtained
E/EGL_emulation(29098): eglQueryContext 32c0  EGL_BAD_ATTRIBUTE
E/EGL_emulation(29098): tid 29695: eglQueryContext(1902): error 0x3004 (EGL_BAD_ATTRIBUTE)
D/SurfaceUtils(29098): connecting to surface 0xc72b1008, reason connectToSurface
I/MediaCodec(29098): [OMX.google.h264.decoder] setting surface generation to 29796358
D/SurfaceUtils(29098): disconnecting from surface 0xc72b1008, reason connectToSurface(reconnect)
D/SurfaceUtils(29098): connecting to surface 0xc72b1008, reason connectToSurface(reconnect)
E/ACodec  (29098): [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
I/VideoFrameDropper(29098): inFrameRateReciprocal:0.041666666666666664 outFrameRateReciprocal:0.041666666666666664
D/MediaCodec(29098): [OMX.google.h264.decoder] setting dataspace on output surface to #104
V/Engine  (29098): new step: 1
I/AudioEngine(29098): process - time stretching - decoderDurationUs:0 encoderDeltaUs:0 stretchFactor:NaN
I/AudioEngine(29098): process - totalInputSize:160 processedTotalInputSize:0 outputSize:2048 inputSize:160
W/AudioEngine(29098): ensureTempBuffer1 - desiredSize:0
W/AudioEngine(29098): ensureTempBuffer1 - creating new buffer.
W/AudioEngine(29098): ensureTempBuffer2 - desiredSize:0
W/AudioEngine(29098): ensureTempBuffer2 - creating new buffer.
V/VideoFrameDropper(29098): RENDERING (first frame) - frameRateReciprocalSum:0.041666666666666664
D/SoftwareRenderer(29098): setting dataspace on output surface to #104
V/VideoDecoderOutput(29098): New frame available
D/ACodec  (29098): dataspace changed to 0x10c10000 (R:2(Limited), P:1(BT709_5), M:1(BT709_5), T:3(SMPTE170M)) (R:2(Limited), S:1(BT709), T:3(SMPTE_170M))
V/Engine  (29098): new step: 2
I/DefaultDataSinkChecks(29098): Output H.264 profile: Baseline Profile
V/DefaultDataSink(29098): Added track #0 with video/avc to muxer
V/DefaultDataSink(29098): Added track #1 with audio/mp4a-latm to muxer
I/MPEG4Writer(29098): limits: 4294967295/0 bytes/us, bit rate: -1 bps and the estimated moov size 3192 bytes
V/VideoFrameDropper(29098): RENDERING - frameRateReciprocalSum:0.041666666666666664
V/VideoDecoderOutput(29098): New frame available
V/Engine  (29098): new step: 3
V/VideoFrameDropper(29098): RENDERING - frameRateReciprocalSum:0.041666666666666664
V/VideoDecoderOutput(29098): New frame available
V/Engine  (29098): new step: 4
I/MPEG4Writer(29098): setStartTimestampUs: 10
I/MPEG4Writer(29098): Earliest track starting time: 10
V/VideoFrameDropper(29098): RENDERING - frameRateReciprocalSum:0.041666666666666664
V/VideoDecoderOutput(29098): New frame available
V/Engine  (29098): new step: 5
V/VideoFrameDropper(29098): RENDERING - frameRateReciprocalSum:0.041666666666666664
V/VideoDecoderOutput(29098): New frame available
V/Engine  (29098): new step: 6
V/VideoFrameDropper(29098): RENDERING - frameRateReciprocalSum:0.041666666666666664
V/VideoDecoderOutput(29098): New frame available
V/Engine  (29098): new step: 7
V/VideoFrameDropper(29098): RENDERING - frameRateReciprocalSum:0.041666666666666664
V/VideoDecoderOutput(29098): New frame available
V/Engine  (29098): new step: 8
V/VideoFrameDropper(29098): RENDERING - frameRateReciprocalSum:0.041666666666666664
V/VideoDecoderOutput(29098): New frame available
V/Engine  (29098): new step: 9
V/VideoFrameDropper(29098): RENDERING - frameRateReciprocalSum:0.041666666666666664
V/VideoDecoderOutput(29098): New frame available
V/Engine  (29098): getTrackProgress - readUs:27230824422, totalUs:27230860000
V/Engine  (29098): getTrackProgress - readUs:27230824422, totalUs:27230860000
V/Engine  (29098): progress - video:0.9999986934676319 audio:0.9999986934676319
V/Engine  (29098): new step: 10
V/VideoFrameDropper(29098): RENDERING - frameRateReciprocalSum:0.041666666666666664
V/VideoDecoderOutput(29098): New frame available
V/Engine  (29098): new step: 11
V/VideoFrameDropper(29098): RENDERING - frameRateReciprocalSum:0.041666666666666664
V/VideoDecoderOutput(29098): New frame available
V/Engine  (29098): new step: 12
V/VideoFrameDropper(29098): RENDERING - frameRateReciprocalSum:0.041666666666666664
V/VideoDecoderOutput(29098): New frame available
V/Engine  (29098): new step: 13
V/VideoFrameDropper(29098): RENDERING - frameRateReciprocalSum:0.041666666666666664
V/VideoDecoderOutput(29098): New frame available
V/Engine  (29098): new step: 14
V/VideoFrameDropper(29098): RENDERING - frameRateReciprocalSum:0.041666666666666664
V/VideoDecoderOutput(29098): New frame available
V/Engine  (29098): new step: 15
V/VideoFrameDropper(29098): RENDERING - frameRateReciprocalSum:0.041666666666666664
V/VideoDecoderOutput(29098): New frame available
V/Engine  (29098): new step: 16
V/VideoFrameDropper(29098): RENDERING - frameRateReciprocalSum:0.041666666666666664
V/VideoDecoderOutput(29098): New frame available
V/Engine  (29098): new step: 17
V/VideoFrameDropper(29098): RENDERING - frameRateReciprocalSum:0.041666666666666664
V/VideoDecoderOutput(29098): New frame available
V/Engine  (29098): new step: 18
V/VideoFrameDropper(29098): RENDERING - frameRateReciprocalSum:0.041666666666666664
V/VideoDecoderOutput(29098): New frame available
V/Engine  (29098): new step: 19
V/VideoFrameDropper(29098): RENDERING - frameRateReciprocalSum:0.041666666666666664
V/VideoDecoderOutput(29098): New frame available
V/Engine  (29098): getTrackProgress - readUs:27230824422, totalUs:27230860000
V/Engine  (29098): getTrackProgress - readUs:27230824422, totalUs:27230860000
V/Engine  (29098): progress - video:0.9999986934676319 audio:0.9999986934676319
V/Engine  (29098): new step: 20
V/VideoFrameDropper(29098): RENDERING - frameRateReciprocalSum:0.041666666666666664
V/VideoDecoderOutput(29098): New frame available
V/Engine  (29098): new step: 21
V/Engine  (29098): new step: 22
V/Engine  (29098): new step: 23
V/Engine  (29098): new step: 24
V/Engine  (29098): new step: 25
V/Engine  (29098): new step: 26
V/Engine  (29098): new step: 27
E/MPEG4Writer(29098): The number of recorded samples is 0
E/MPEG4Writer(29098): 0 frames to dump timeStamps in Audio track 
W/MPEG4Writer(29098): 0-duration samples found: 1
W/MPEG4Writer(29098): 0-duration samples found: 1
I/MPEG4Writer(29098): Received total/0-length (20/1) buffers and encoded 20 frames. - Video
I/MPEG4Writer(29098): Received total/0-length (0/1) buffers and encoded 0 frames. - Audio
I/MPEG4Writer(29098): Audio track drift time: 0 us
D/MPEG4Writer(29098): Video track stopping. Stop source
D/MPEG4Writer(29098): Video track source stopping
D/MPEG4Writer(29098): Video track source stopped
D/MPEG4Writer(29098): Video track stopped. Stop source
D/MPEG4Writer(29098): Audio track stopping. Stop source
D/MPEG4Writer(29098): Audio track source stopping
D/MPEG4Writer(29098): Audio track source stopped
D/MPEG4Writer(29098): Audio track stopped. Stop source
D/MPEG4Writer(29098): Duration from tracks range is [0, 27230859622] us
D/MPEG4Writer(29098): Stopping writer thread
D/MPEG4Writer(29098): 0 chunks are written in the last batch
D/MPEG4Writer(29098): Writer thread stopped
E/Surface (29098): getSlotFromBufferLocked: unknown buffer: 0x0
D/SurfaceUtils(29098): disconnecting from surface 0xc72b1008, reason disconnectFromSurface
E/MediaMuxer(29098): stop() is called in invalid state 3
W/DefaultDataSink(29098): Failed to release the muxer.
W/DefaultDataSink(29098): java.lang.IllegalStateException: Failed to stop the muxer
W/DefaultDataSink(29098): 	at android.media.MediaMuxer.nativeStop(Native Method)
W/DefaultDataSink(29098): 	at android.media.MediaMuxer.stop(MediaMuxer.java:466)
W/DefaultDataSink(29098): 	at android.media.MediaMuxer.release(MediaMuxer.java:706)
W/DefaultDataSink(29098): 	at com.otaliastudios.transcoder.sink.DefaultDataSink.release(DefaultDataSink.java:189)
W/DefaultDataSink(29098): 	at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:394)
W/DefaultDataSink(29098): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:134)
W/DefaultDataSink(29098): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:124)
W/DefaultDataSink(29098): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/DefaultDataSink(29098): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/DefaultDataSink(29098): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/DefaultDataSink(29098): 	at java.lang.Thread.run(Thread.java:919)
E/Transcoder(29098): Fatal error while transcoding, this might be invalid format or bug in engine or Android.
E/Transcoder(29098): java.lang.IllegalStateException: Failed to stop the muxer
E/Transcoder(29098): 	at android.media.MediaMuxer.nativeStop(Native Method)
E/Transcoder(29098): 	at android.media.MediaMuxer.stop(MediaMuxer.java:466)
E/Transcoder(29098): 	at com.otaliastudios.transcoder.sink.DefaultDataSink.stop(DefaultDataSink.java:183)
E/Transcoder(29098): 	at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:388)
E/Transcoder(29098): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:134)
E/Transcoder(29098): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:124)
E/Transcoder(29098): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/Transcoder(29098): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Transcoder(29098): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Transcoder(29098): 	at java.lang.Thread.run(Thread.java:919)`

Any help or pointers would be greatly appreciated.

**Comment by jonataslaw** [comment]
Fixed on 2.1.1
