### ISSUE TITLE
Can't compress video

### ISSUE THREAD

**Issue by TungWang** [jonataslaw/VideoCompress#65]
This is a really great plugin.
It's stable until today, and i don't know why.
Here's the logs.

E/MethodChannel#video_compress( 7633): Failed to handle method call
E/MethodChannel#video_compress( 7633): kotlin.KotlinNullPointerException
E/MethodChannel#video_compress( 7633): 	at com.example.video_compress.VideoCompressPlugin.onMethodCall(VideoCompressPlugin.kt:83)
E/MethodChannel#video_compress( 7633): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#video_compress( 7633): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#video_compress( 7633): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#video_compress( 7633): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#video_compress( 7633): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#video_compress( 7633): 	at android.os.Looper.loop(Looper.java:163)
E/MethodChannel#video_compress( 7633): 	at android.app.ActivityThread.main(ActivityThread.java:6732)
E/MethodChannel#video_compress( 7633): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#video_compress( 7633): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#video_compress( 7633): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter ( 7633): Error from VideoCompress: 
I/flutter ( 7633):       Method: compressVideo
I/flutter ( 7633):       PlatformException(error, null, null, kotlin.KotlinNullPointerException
I/flutter ( 7633): 	at com.example.video_compress.VideoCompressPlugin.onMethodCall(VideoCompressPlugin.kt:83)
I/flutter ( 7633): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
I/flutter ( 7633): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
I/flutter ( 7633): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
I/flutter ( 7633): 	at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter ( 7633): 	at android.os.MessageQueue.next(MessageQueue.java:326)
I/flutter ( 7633): 	at android.os.Looper.loop(Looper.java:163)
I/flutter ( 7633): 	at android.app.ActivityThread.main(ActivityThread.java:6732)
I/flutter ( 7633): 	at java.lang.reflect.Method.invoke(Native Method)
I/flutter ( 7633): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
I/flutter ( 7633): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter ( 7633): )
E/flutter ( 7633): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'file' was called on null.
E/flutter ( 7633): Receiver: null
E/flutter ( 7633): Tried calling: file
E/flutter ( 7633): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 7633): #1      _RemarkContainerState._onPressedAddAttachment.<anonymous closure>.<anonymous closure> (package:home_companion/widgets/remark_container.dart:150:28)
E/flutter ( 7633): <asynchronous suspension>
E/flutter ( 7633): #2      _RemarkContainerState._onPressedAddAttachment.<anonymous closure>.<anonymous closure> (package:home_companion/widgets/remark_container.dart)
E/flutter ( 7633): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter ( 7633): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter ( 7633): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter ( 7633): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter ( 7633): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter ( 7633): #8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
E/flutter ( 7633): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter ( 7633): #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
E/flutter ( 7633): #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter ( 7633): #12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter ( 7633): #13     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter ( 7633): #14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter ( 7633): #15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter ( 7633): #16     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 7633): #17     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 7633): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 7633): #19     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter ( 7633): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter ( 7633): 

Could anybody help me to solve it?

**Comment by mpigorini** [comment]
I added includeAudio param to the compressVideo method

>   MediaInfo mediaInfo = await VideoCompress.compressVideo(
       videoPath,
        quality: VideoQuality.LowQuality,
        deleteOrigin: false,
        **includeAudio: true**
      );

**Comment by drexel-ue** [comment]
> I added includeAudio param to the compressVideo method
> 
> > MediaInfo mediaInfo = await VideoCompress.compressVideo(
> > videoPath,
> > quality: VideoQuality.LowQuality,
> > deleteOrigin: false,
> > **includeAudio: true**
> > );

can confirm

**Comment by shaohui93** [comment]
> > 我在includeVideo方法中添加了includeAudio参数
> > > MediaInfo mediaInfo =等待VideoCompress.compressVideo（
> > > videoPath，
> > > quality：VideoQuality.LowQuality，
> > > deleteOrigin：false，
> > > **includeAudio：true** 
> > > ）;
> 
> 可以确认


This solves my problem

**Comment by jonataslaw** [comment]
Fixed on 2.1.1
