### ISSUE TITLE
Thank You - Note to creator of plugin

### ISSUE THREAD

**Issue by khainhero** [jonataslaw/VideoCompress#7]
This is a brilliant plug-in. I was using FFMPEG which works fine the way i figured out the balance of quality/compression speed and final compressed output file size.

This plugin is very lightweight and saves me about 7.5 MB for final APK size(Very good!)

Obviously I found many issues but I think you can fix them very easily. Some could be related to how Video_Player plugin from google displays the video because on Chrome it works very good across the board.

again very nice job to you and thank you for bringing this to the flutter community by porting it.

**Comment by jonataslaw** [comment]
> This is a brilliant plug-in. I was using FFMPEG which works fine the way i figured out the balance of quality/compression speed and final compressed output file size.
> 
> This plugin is very lightweight and saves me about 7.5 MB for final APK size(Very good!)
> 
> Obviously I found many issues but I think you can fix them very easily. Some could be related to how Video_Player plugin from google displays the video because on Chrome it works very good across the board.
> 
> again very nice job to you and thank you for bringing this to the flutter community by porting it.

Thanks for opening the issues.
I obviously didn't have the opportunity to test it on all devices, and its issues helped me with that.
During this week I have a lot of work, but I will fix them all by the weekend.

**Comment by khainhero** [comment]
no problem

btw I listed the OS(iOS or android) in title of the issues

thanks again 👍  you can close this anytime
