### ISSUE TITLE
Video compress failed on LG g8x android 10

### ISSUE THREAD

**Issue by tanvish99** [jonataslaw/VideoCompress#72]
I/flutter ( 9573): VideoCompress: You can try to subscribe to the 
I/flutter ( 9573):       compressProgress$ stream to know the compressing state.
V/LGCodecAdapter( 9573): convertMetaDataToMessage MetaDataBase
V/LGCodecOSAL( 9573): Called LGCodeConvertMetaDataBaseToMessage
V/LGCodecAdapter( 9573): convertMetaDataToMessage MetaDataBase
V/LGCodecOSAL( 9573): Called LGCodeConvertMetaDataBaseToMessage
E/Transcoder( 9573): Fatal error while transcoding, this might be invalid format or bug in engine or Android.
E/Transcoder( 9573): java.lang.IllegalArgumentException
E/Transcoder( 9573): 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:183)
E/Transcoder( 9573): 	at com.otaliastudios.transcoder.source.UriDataSource.applyRetriever(UriDataSource.java:33)
E/Transcoder( 9573): 	at com.otaliastudios.transcoder.source.DefaultDataSource.ensureMetadata(DefaultDataSource.java:41)
E/Transcoder( 9573): 	at com.otaliastudios.transcoder.source.DefaultDataSource.getLocation(DefaultDataSource.java:138)
E/Transcoder( 9573): 	at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:316)
E/Transcoder( 9573): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:134)
E/Transcoder( 9573): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:124)
E/Transcoder( 9573): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/Transcoder( 9573): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Transcoder( 9573): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Transcoder( 9573): 	at java.lang.Thread.run(Thread.java:919)

**Comment by tanvish99** [comment]
MediaInfo mediaInfo = await VideoCompress.compressVideo(
                                                                  filename,
                                                                  quality:
                                                                      VideoQuality
                                                                          .DefaultQuality,
                                                                  deleteOrigin:
                                                                      false,
                                                                  includeAudio:
                                                                      true // It's false by default
                                                                  );
this command was used to compress video

**Comment by jonataslaw** [comment]
Fixed on 2.1.1

**Comment by NicolasCELLA** [comment]
Same problem on 2.1.1

**Comment by litzbalane2017** [comment]
Good Day.

I am also encountering the same issue for Samsung Galaxy J7 Prime android version 6.0.1. Below are the logs:

I/flutter (26470): VideoCompress: You can try to subscribe to the 
I/flutter (26470):       compressProgress$ stream to know the compressing state.
E/WVMExtractor(26470): Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found
I/DefaultVideoStrategy(26470): Input width&height: 1920x1080
I/DefaultVideoStrategy(26470): Output width&height: 1280x720
V/Engine  (26470): Duration (us): 92318000
V/Engine  (26470): new step: 0
I/ACodec  (26470):  [] Now uninitialized
I/ACodec  (26470): [] onAllocateComponent
I/OMXClient(26470): Using client-side OMX mux.
I/EXYNOS_COMP_REGS(26470): Loading the library: libOMX.Exynos.AVC.Decoder.so
I/EXYNOS_COMP_REGS(26470): Loading the library: libOMX.Exynos.AVC.Encoder.so
I/EXYNOS_COMP_REGS(26470): Loading the library: libOMX.Exynos.HEVC.Decoder.so
I/EXYNOS_COMP_REGS(26470): Loading the library: libOMX.Exynos.HEVC.Encoder.so
I/EXYNOS_COMP_REGS(26470): Loading the library: libOMX.Exynos.MPEG4.Decoder.so
I/EXYNOS_COMP_REGS(26470): Loading the library: libOMX.Exynos.MPEG4.Encoder.so
I/EXYNOS_COMP_REGS(26470): Loading the library: libOMX.Exynos.VP8.Decoder.so
I/EXYNOS_COMP_REGS(26470): Loading the library: libOMX.Exynos.VP8.Encoder.so
I/EXYNOS_COMP_REGS(26470): Loading the library: libOMX.Exynos.WMV.Decoder.so
I/SEC_COMP_REGS(26470): Loading the library: libsomx263dsw.so
I/SEC_COMP_REGS(26470): Loading the library: libsomx264dsw.so
I/SEC_COMP_REGS(26470): Loading the library: libsomxhevcdsw.so
I/SEC_COMP_REGS(26470): Loading the library: libsomxmp4vdsw.so
I/SEC_COMP_REGS(26470): Loading the library: libsomxmp43d.so
I/SEC_COMP_REGS(26470): Loading the library: libsomxvc1dsw.so
I/SEC_COMP_REGS(26470): Loading the library: libsomxvp8d.so
I/SEC_COMP_REGS(26470): Loading the library: libsomxwmv7d.so
I/SEC_COMP_REGS(26470): Loading the library: libsomxwmv8d.so
I/SEC_COMP_REGS(26470): Loading the library: libsomxamrd.so
I/SEC_COMP_REGS(26470): Loading the library: libsomxadpcmd.so
I/SEC_COMP_REGS(26470): Loading the library: libsomxflacd.so
I/SEC_COMP_REGS(26470): Loading the library: libsomxaacd.so
I/SEC_COMP_REGS(26470): Loading the library: libsomxmp3d.so
I/SEC_COMP_REGS(26470): Loading the library: libsomxwmad.so
I/SEC_COMP_REGS(26470): Loading the library: libsomxaace.so
I/SEC_COMP_REGS(26470): Loading the library: libsomxnaace.so
I/SEC_COMP_REGS(26470): Loading the library: libsomxvencsw.so
I/ACodec  (26470): [OMX.google.aac.encoder] Now Loaded
I/ACodec  (26470): [OMX.google.aac.encoder] Now Loaded->Idle
I/ACodec  (26470):  [] Now uninitialized
I/ACodec  (26470): [OMX.google.aac.encoder] Now Idle->Executing
I/ACodec  (26470): [] onAllocateComponent
I/OMXClient(26470): Using client-side OMX mux.
I/ACodec  (26470): [OMX.google.aac.encoder] Now Executing
W/SoftAACEncoder2(26470): Requested bitrate 1152000 unsupported, using 576000
I/ACodec  (26470): [OMX.SEC.aac.dec] Now Loaded
I/ACodec  (26470): [OMX.SEC.aac.dec] Now Loaded->Idle
I/ACodec  (26470):  [] Now uninitialized
I/ACodec  (26470): [] onAllocateComponent
I/OMXClient(26470): Using client-side OMX mux.
I/ACodec  (26470): [OMX.Exynos.AVC.Encoder] Now Loaded
I/ACodec  (26470): [OMX.SEC.aac.dec] Now Idle->Executing
W/ACodec  (26470): do not know color format 0x7f000011 = 2130706449
W/ACodec  (26470): do not know color format 0x10 = 16
W/ACodec  (26470): do not know color format 0x7f00a000 = 2130747392
W/ACodec  (26470): do not know color format 0x7f000789 = 2130708361
I/ACodec  (26470): [OMX.SEC.aac.dec] Now Executing
I/ACodec  (26470): setupVideoEncoder succeeded
W/ACodec  (26470): do not know color format 0x7f000789 = 2130708361
D/libEGL  (26470): eglInitialize EGLDisplay = 0xc8974214
D/mali_winsys(26470): new_window_surface returns 0x3000,  [1280x720]-format:1
I/ACodec  (26470): [OMX.Exynos.AVC.Encoder] Now Loaded->Idle
I/ACodec  (26470): [OMX.Exynos.AVC.Encoder] Now Idle->Executing
I/ACodec  (26470): [OMX.Exynos.AVC.Encoder] Now Executing
I/ACodec  (26470):  [] Now uninitialized
I/ACodec  (26470): [] onAllocateComponent
I/OMXClient(26470): Using client-side OMX mux.
I/ACodec  (26470): [OMX.Exynos.avc.dec] Now Loaded
I/MediaCodec(26470): [OMX.Exynos.avc.dec] setting surface generation to 27105283
I/ACodec  (26470): can't find wfdsink-exynos-enable
E/ACodec  (26470):  configureCodec multi window instance fail  appPid : 26470
E/ACodec  (26470): [OMX.Exynos.avc.dec] configureCodec returning error -5001
E/ACodec  (26470): signalError(omxError 0x80001001, internalError -5001)
E/MediaCodec(26470): Codec reported err 0xffffec77, actionCode 0, while in state 3
E/MediaCodec(26470): configure failed with err 0xffffec77, resetting...
I/ACodec  (26470):  [OMX.Exynos.avc.dec] Now uninitialized
I/ACodec  (26470):  [] Now kWhatShutdownCompleted event : 7153
I/MediaCodec(26470): Codec shutdown complete
I/ACodec  (26470):  [] Now uninitialized
I/ACodec  (26470): [] onAllocateComponent
I/OMXClient(26470): Using client-side OMX mux.
I/ACodec  (26470): [OMX.Exynos.avc.dec] Now Loaded
E/Transcoder(26470): Fatal error while transcoding, this might be invalid format or bug in engine or Android.
E/Transcoder(26470): android.media.MediaCodec$CodecException: Error 0xffffec77
E/Transcoder(26470): 	at android.media.MediaCodec.native_configure(Native Method)
E/Transcoder(26470): 	at android.media.MediaCodec.configure(MediaCodec.java:1778)
E/Transcoder(26470): 	at com.otaliastudios.transcoder.transcode.VideoTrackTranscoder.onConfigureDecoder(VideoTrackTranscoder.java:105)
E/Transcoder(26470): 	at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.setUp(BaseTrackTranscoder.java:75)
E/Transcoder(26470): 	at com.otaliastudios.transcoder.engine.Engine.openCurrentStep(Engine.java:194)
E/Transcoder(26470): 	at com.otaliastudios.transcoder.engine.Engine.getCurrentTrackTranscoder(Engine.java:223)
E/Transcoder(26470): 	at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:371)
E/Transcoder(26470): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:134)
E/Transcoder(26470): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:124)
E/Transcoder(26470): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/Transcoder(26470): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/Transcoder(26470): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/Transcoder(26470): 	at java.lang.Thread.run(Thread.java:818)
I/flutter (26470): null
W/AMessage(26470): failed to deliver message as target handler 23 is gone.
W/libc    (26470): It seems that pthread_join() is not invoked or PTHREAD_ATTR_FLAG_DETACHED is not set.
W/libc    (26470):     pthread tid          : 27755
W/libc    (26470):     pthread start_routine: 0xdea773e1
W/libc    (26470): It seems that pthread_join() is not invoked or PTHREAD_ATTR_FLAG_DETACHED is not set.
W/libc    (26470):     pthread tid          : 27761
W/libc    (26470):     pthread start_routine: 0xdea773e1
W/libc    (26470): It seems that pthread_join() is not invoked or PTHREAD_ATTR_FLAG_DETACHED is not set.
W/libc    (26470):     pthread tid          : 26544
W/libc    (26470):     pthread start_routine: 0xdea773e1

Thank you.

**Comment by jonataslaw** [comment]
> Good Day.
> 
> I am also encountering the same issue for Samsung Galaxy J7 Prime android version 6.0.1. Below are the logs:
> 
> I/flutter (26470): VideoCompress: You can try to subscribe to the
> I/flutter (26470): compressProgress$ stream to know the compressing state.
> E/WVMExtractor(26470): Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found
> I/DefaultVideoStrategy(26470): Input width&height: 1920x1080
> I/DefaultVideoStrategy(26470): Output width&height: 1280x720
> V/Engine (26470): Duration (us): 92318000
> V/Engine (26470): new step: 0
> I/ACodec (26470): [] Now uninitialized
> I/ACodec (26470): [] onAllocateComponent
> I/OMXClient(26470): Using client-side OMX mux.
> I/EXYNOS_COMP_REGS(26470): Loading the library: libOMX.Exynos.AVC.Decoder.so
> I/EXYNOS_COMP_REGS(26470): Loading the library: libOMX.Exynos.AVC.Encoder.so
> I/EXYNOS_COMP_REGS(26470): Loading the library: libOMX.Exynos.HEVC.Decoder.so
> I/EXYNOS_COMP_REGS(26470): Loading the library: libOMX.Exynos.HEVC.Encoder.so
> I/EXYNOS_COMP_REGS(26470): Loading the library: libOMX.Exynos.MPEG4.Decoder.so
> I/EXYNOS_COMP_REGS(26470): Loading the library: libOMX.Exynos.MPEG4.Encoder.so
> I/EXYNOS_COMP_REGS(26470): Loading the library: libOMX.Exynos.VP8.Decoder.so
> I/EXYNOS_COMP_REGS(26470): Loading the library: libOMX.Exynos.VP8.Encoder.so
> I/EXYNOS_COMP_REGS(26470): Loading the library: libOMX.Exynos.WMV.Decoder.so
> I/SEC_COMP_REGS(26470): Loading the library: libsomx263dsw.so
> I/SEC_COMP_REGS(26470): Loading the library: libsomx264dsw.so
> I/SEC_COMP_REGS(26470): Loading the library: libsomxhevcdsw.so
> I/SEC_COMP_REGS(26470): Loading the library: libsomxmp4vdsw.so
> I/SEC_COMP_REGS(26470): Loading the library: libsomxmp43d.so
> I/SEC_COMP_REGS(26470): Loading the library: libsomxvc1dsw.so
> I/SEC_COMP_REGS(26470): Loading the library: libsomxvp8d.so
> I/SEC_COMP_REGS(26470): Loading the library: libsomxwmv7d.so
> I/SEC_COMP_REGS(26470): Loading the library: libsomxwmv8d.so
> I/SEC_COMP_REGS(26470): Loading the library: libsomxamrd.so
> I/SEC_COMP_REGS(26470): Loading the library: libsomxadpcmd.so
> I/SEC_COMP_REGS(26470): Loading the library: libsomxflacd.so
> I/SEC_COMP_REGS(26470): Loading the library: libsomxaacd.so
> I/SEC_COMP_REGS(26470): Loading the library: libsomxmp3d.so
> I/SEC_COMP_REGS(26470): Loading the library: libsomxwmad.so
> I/SEC_COMP_REGS(26470): Loading the library: libsomxaace.so
> I/SEC_COMP_REGS(26470): Loading the library: libsomxnaace.so
> I/SEC_COMP_REGS(26470): Loading the library: libsomxvencsw.so
> I/ACodec (26470): [OMX.google.aac.encoder] Now Loaded
> I/ACodec (26470): [OMX.google.aac.encoder] Now Loaded->Idle
> I/ACodec (26470): [] Now uninitialized
> I/ACodec (26470): [OMX.google.aac.encoder] Now Idle->Executing
> I/ACodec (26470): [] onAllocateComponent
> I/OMXClient(26470): Using client-side OMX mux.
> I/ACodec (26470): [OMX.google.aac.encoder] Now Executing
> W/SoftAACEncoder2(26470): Requested bitrate 1152000 unsupported, using 576000
> I/ACodec (26470): [OMX.SEC.aac.dec] Now Loaded
> I/ACodec (26470): [OMX.SEC.aac.dec] Now Loaded->Idle
> I/ACodec (26470): [] Now uninitialized
> I/ACodec (26470): [] onAllocateComponent
> I/OMXClient(26470): Using client-side OMX mux.
> I/ACodec (26470): [OMX.Exynos.AVC.Encoder] Now Loaded
> I/ACodec (26470): [OMX.SEC.aac.dec] Now Idle->Executing
> W/ACodec (26470): do not know color format 0x7f000011 = 2130706449
> W/ACodec (26470): do not know color format 0x10 = 16
> W/ACodec (26470): do not know color format 0x7f00a000 = 2130747392
> W/ACodec (26470): do not know color format 0x7f000789 = 2130708361
> I/ACodec (26470): [OMX.SEC.aac.dec] Now Executing
> I/ACodec (26470): setupVideoEncoder succeeded
> W/ACodec (26470): do not know color format 0x7f000789 = 2130708361
> D/libEGL (26470): eglInitialize EGLDisplay = 0xc8974214
> D/mali_winsys(26470): new_window_surface returns 0x3000, [1280x720]-format:1
> I/ACodec (26470): [OMX.Exynos.AVC.Encoder] Now Loaded->Idle
> I/ACodec (26470): [OMX.Exynos.AVC.Encoder] Now Idle->Executing
> I/ACodec (26470): [OMX.Exynos.AVC.Encoder] Now Executing
> I/ACodec (26470): [] Now uninitialized
> I/ACodec (26470): [] onAllocateComponent
> I/OMXClient(26470): Using client-side OMX mux.
> I/ACodec (26470): [OMX.Exynos.avc.dec] Now Loaded
> I/MediaCodec(26470): [OMX.Exynos.avc.dec] setting surface generation to 27105283
> I/ACodec (26470): can't find wfdsink-exynos-enable
> E/ACodec (26470): configureCodec multi window instance fail appPid : 26470
> E/ACodec (26470): [OMX.Exynos.avc.dec] configureCodec returning error -5001
> E/ACodec (26470): signalError(omxError 0x80001001, internalError -5001)
> E/MediaCodec(26470): Codec reported err 0xffffec77, actionCode 0, while in state 3
> E/MediaCodec(26470): configure failed with err 0xffffec77, resetting...
> I/ACodec (26470): [OMX.Exynos.avc.dec] Now uninitialized
> I/ACodec (26470): [] Now kWhatShutdownCompleted event : 7153
> I/MediaCodec(26470): Codec shutdown complete
> I/ACodec (26470): [] Now uninitialized
> I/ACodec (26470): [] onAllocateComponent
> I/OMXClient(26470): Using client-side OMX mux.
> I/ACodec (26470): [OMX.Exynos.avc.dec] Now Loaded
> E/Transcoder(26470): Fatal error while transcoding, this might be invalid format or bug in engine or Android.
> E/Transcoder(26470): android.media.MediaCodec$CodecException: Error 0xffffec77
> E/Transcoder(26470): at android.media.MediaCodec.native_configure(Native Method)
> E/Transcoder(26470): at android.media.MediaCodec.configure(MediaCodec.java:1778)
> E/Transcoder(26470): at com.otaliastudios.transcoder.transcode.VideoTrackTranscoder.onConfigureDecoder(VideoTrackTranscoder.java:105)
> E/Transcoder(26470): at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.setUp(BaseTrackTranscoder.java:75)
> E/Transcoder(26470): at com.otaliastudios.transcoder.engine.Engine.openCurrentStep(Engine.java:194)
> E/Transcoder(26470): at com.otaliastudios.transcoder.engine.Engine.getCurrentTrackTranscoder(Engine.java:223)
> E/Transcoder(26470): at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:371)
> E/Transcoder(26470): at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:134)
> E/Transcoder(26470): at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:124)
> E/Transcoder(26470): at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> E/Transcoder(26470): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> E/Transcoder(26470): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> E/Transcoder(26470): at java.lang.Thread.run(Thread.java:818)
> I/flutter (26470): null
> W/AMessage(26470): failed to deliver message as target handler 23 is gone.
> W/libc (26470): It seems that pthread_join() is not invoked or PTHREAD_ATTR_FLAG_DETACHED is not set.
> W/libc (26470): pthread tid : 27755
> W/libc (26470): pthread start_routine: 0xdea773e1
> W/libc (26470): It seems that pthread_join() is not invoked or PTHREAD_ATTR_FLAG_DETACHED is not set.
> W/libc (26470): pthread tid : 27761
> W/libc (26470): pthread start_routine: 0xdea773e1
> W/libc (26470): It seems that pthread_join() is not invoked or PTHREAD_ATTR_FLAG_DETACHED is not set.
> W/libc (26470): pthread tid : 26544
> W/libc (26470): pthread start_routine: 0xdea773e1
> 
> Thank you.


Hi, this if you search for:

`Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found`


you’ll find a ton of errors about this. Some devices have custom rooms that suppress audio compression libraries, low-cost samsung and xiaomi devices seem to be the most frequent. These devices simply cannot do this, because they have excluded the native android library responsible for this.
