### ISSUE TITLE
Crash compression on android

### ISSUE THREAD

**Issue by RenanDelfanti** [jonataslaw/VideoCompress#84]
I/flutter ( 7512): VideoCompress: You can try to subscribe to the 
I/flutter ( 7512):       compressProgress$ stream to know the compressing state.
I/flutter ( 7512): Error from VideoCompress: 
I/flutter ( 7512):       Method: getMediaInfo
I/flutter ( 7512):       PlatformException(error, setDataSource failed: status = 0x80000000, null, java.lang.RuntimeException: setDataSource failed: status = 0x80000000
I/flutter ( 7512):      at android.media.MediaMetadataRetriever.setDataSource(Native Method)
I/flutter ( 7512):      at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:82)
I/flutter ( 7512):      at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:173)
I/flutter ( 7512):      at com.example.video_compress.Utility.getMediaInfoJson(Utility.kt:38)
I/flutter ( 7512):      at com.example.video_compress.VideoCompressPlugin.onMethodCall(VideoCompressPlugin.kt:63)
I/flutter ( 7512):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
I/flutter ( 7512):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
I/flutter ( 7512):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
I/flutter ( 7512):      at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter ( 7512):      at android.os.MessageQueue.next(MessageQueue.java:336)
I/flutter ( 7512):      at android.os.Looper.loop(Looper.java:197)
I/flutter ( 7512):      at android.app.ActivityThread.main(ActivityThread.java:8167)
I/flutter ( 7512):      at java.lang.reflect.Method.invoke(Native Method)
I/flutter ( 7512):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
I/flutter ( 7512):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
I/flutter ( 7512): )

**Comment by denes16** [comment]
How you solve this?
