### ISSUE TITLE
Support null-safety

### ISSUE THREAD

**Issue by al8n** [jonataslaw/VideoCompress#86]
Thanks for the amazing package. Is there a plan to support the null-safety version?

**Comment by petoknm** [comment]
Null-safety is now officially out! It would be great if this package supported it.

**Comment by vanfresh** [comment]
I am receiving this error using null-safety

`type 'Future<String?>' is not a subtype of type 'FutureOr<String>' in type cast
I/flutter (20186): #0      Compress.getMediaInfo (package:video_compress/src/video_compress/video_compressor.dart:98:76)`

**Comment by exmozz** [comment]
> I am receiving this error using null-safety to get `MediaInfo`
> 
> `type 'Future<String?>' is not a subtype of type 'FutureOr<String>' in type cast I/flutter (20186): #0 Compress.getMediaInfo (package:video_compress/src/video_compress/video_compressor.dart:98:76)`

Have same issue with both getMediaInfo and getFileThumbnail.

**Comment by yanivshaked** [comment]
Seems related to the following PR:
https://github.com/jonataslaw/VideoCompress/pull/103

**Comment by ccamba** [comment]
is this project alive?

**Comment by yanivshaked** [comment]
Use the latest version for a fix for all of the above issues, until @jonataslaw provides a new release:
```
video_compress:
  git:
    url: https://github.com/jonataslaw/VideoCompress
    ref: "583e700"
```

**Comment by ccamba** [comment]
Hi @yanivshaked, 
I had no problems on iOS but in Android:
VideoCompressPlugin.kt: (194, 22): Cannot access 'init': it is private in 'VideoCompressPlugin' 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':video_compress:compileDebugKotlin'.

**Comment by ccamba** [comment]
I was referencing version 3.0.0 in cache, removing it corrected
