### ISSUE TITLE
iOS - Audio not included by default

### ISSUE THREAD

**Issue by khainhero** [jonataslaw/VideoCompress#9]
Audio is not included by default

Have to include:

`includeAudio: true`

example:

`MediaInfo _compressedVideo = await videoCompress.compressVideo(originalVideoPath, includeAudio: true,);`

**Comment by jonataslaw** [comment]
> Audio is not included by default
> 
> Have to include:
> 
> `includeAudio: true`
> 
> example:
> 
> `MediaInfo _compressedVideo = await videoCompress.compressVideo(originalVideoPath, includeAudio: true,);`

On android or iOS?
I will fix this

**Comment by khainhero** [comment]
> > Audio is not included by default
> > Have to include:
> > `includeAudio: true`
> > example:
> > `MediaInfo _compressedVideo = await videoCompress.compressVideo(originalVideoPath, includeAudio: true,);`
> 
> On android or iOS?
> I will fix this

iOS only
